-- ReportaTarija - esquema y datos demo para InsForge/PostgreSQL.
-- Ejecutar desde InsForge MCP con run_raw_sql o desde un cliente PostgreSQL.
-- Nota: la tabla users es el perfil operativo; las credenciales reales viven en InsForge Auth.

create extension if not exists pgcrypto;

create table if not exists areas (
  id integer generated by default as identity primary key,
  name text not null unique,
  code text unique,
  description text,
  is_active boolean not null default true,
  created_at timestamp default now()
);

create table if not exists categories (
  id integer generated by default as identity primary key,
  name text not null,
  code text not null unique,
  description text,
  default_area_id integer references areas(id),
  is_active boolean not null default true,
  created_at timestamp default now()
);

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text unique not null,
  phone text,
  role text not null check (role in ('CITIZEN', 'ADMIN', 'FUNCIONARIO', 'TECNICO', 'RESPONSABLE_AREA')),
  area_id integer references areas(id),
  is_active boolean not null default true,
  created_at timestamp default now(),
  updated_at timestamp default now(),
  reputation_points integer not null default 0
);

create table if not exists reports (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  category_id integer not null references categories(id),
  citizen_id uuid references users(id),
  assigned_to uuid references users(id),
  assigned_area_id integer references areas(id),
  status text not null default 'PENDIENTE'
    check (status in ('PENDIENTE', 'EN_REVISION', 'ASIGNADO', 'EN_PROCESO', 'RESUELTO', 'RECHAZADO')),
  latitude numeric(10, 8),
  longitude numeric(11, 8),
  address text,
  neighborhood text,
  priority text default 'MEDIA'
    check (priority in ('BAJA', 'MEDIA', 'ALTA', 'URGENTE')),
  created_at timestamp default now(),
  updated_at timestamp default now(),
  resolved_at timestamp
);

create table if not exists evidences (
  id integer generated by default as identity primary key,
  report_id uuid not null references reports(id) on delete cascade,
  file_url text not null,
  file_name text,
  file_type text,
  uploaded_by uuid references users(id),
  created_at timestamp default now()
);

create table if not exists tracking (
  id integer generated by default as identity primary key,
  report_id uuid not null references reports(id) on delete cascade,
  previous_status text,
  new_status text not null,
  comment text,
  changed_by uuid references users(id),
  created_at timestamp default now()
);

create table if not exists notifications (
  id integer generated by default as identity primary key,
  user_id uuid references users(id),
  report_id uuid references reports(id) on delete cascade,
  title text not null,
  message text not null,
  type text not null default 'INFO' check (type in ('INFO', 'WARNING', 'SUCCESS', 'ERROR')),
  is_read boolean not null default false,
  created_at timestamp default now()
);

create index if not exists idx_reports_category_id on reports(category_id);
create index if not exists idx_reports_created_at on reports(created_at desc);
create index if not exists idx_reports_status on reports(status);
create index if not exists idx_tracking_report_id on tracking(report_id);
create index if not exists idx_notifications_user_id on notifications(user_id);

create or replace function populate_notification_user_id()
returns trigger as $$
begin
  if new.user_id is null and new.report_id is not null then
    select assigned_to into new.user_id
    from reports
    where id = new.report_id;
  end if;

  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_populate_notification_user_id on notifications;
create trigger trg_populate_notification_user_id
before insert on notifications
for each row
execute function populate_notification_user_id();

insert into areas (code, name, description) values
  ('OBRAS_PUBLICAS', 'Obras Publicas', 'Atencion de baches, calles danadas y obras urbanas'),
  ('ALUMBRADO_PUBLICO', 'Alumbrado Publico', 'Atencion de luminarias y problemas electricos urbanos'),
  ('ASEO_URBANO', 'Aseo Urbano', 'Atencion de basura acumulada y limpieza urbana'),
  ('MOVILIDAD_URBANA', 'Movilidad Urbana', 'Atencion de semaforos, senalizacion y trafico'),
  ('MEDIO_AMBIENTE', 'Medio Ambiente', 'Atencion de problemas ambientales'),
  ('ATENCION_CIUDADANA', 'Atencion Ciudadana', 'Recepcion y seguimiento general de reportes')
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  is_active = true;

insert into categories (code, name, description, default_area_id) values
  ('BACHE', 'Bache', 'Baches o danos en calles', (select id from areas where code = 'OBRAS_PUBLICAS')),
  ('ALUMBRADO_PUBLICO', 'Alumbrado publico', 'Fallas en luminarias o postes de luz', (select id from areas where code = 'ALUMBRADO_PUBLICO')),
  ('BASURA_ACUMULADA', 'Basura acumulada', 'Acumulacion de basura en espacios publicos', (select id from areas where code = 'ASEO_URBANO')),
  ('FUGA_DE_AGUA', 'Fuga de agua', 'Fugas o problemas relacionados con agua', (select id from areas where code = 'OBRAS_PUBLICAS')),
  ('SEMAFORO_DANADO', 'Semaforo danado', 'Semaforos apagados, danados o con fallas', (select id from areas where code = 'MOVILIDAD_URBANA')),
  ('OTROS', 'Otros', 'Otros problemas urbanos', (select id from areas where code = 'ATENCION_CIUDADANA'))
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  default_area_id = excluded.default_area_id,
  is_active = true;

insert into users (id, full_name, email, role, area_id, is_active) values
  ('00000000-0000-4000-8000-000000000001', 'Admin Municipal', 'admin@reportatarija.bo', 'ADMIN', null, true),
  ('00000000-0000-4000-8000-000000000002', 'Funcionario Obras Publicas', 'obras@reportatarija.bo', 'FUNCIONARIO', (select id from areas where code = 'OBRAS_PUBLICAS'), true),
  ('00000000-0000-4000-8000-000000000003', 'Funcionario Alumbrado', 'alumbrado@reportatarija.bo', 'FUNCIONARIO', (select id from areas where code = 'ALUMBRADO_PUBLICO'), true),
  ('00000000-0000-4000-8000-000000000004', 'Vecino Demo', 'vecino.demo@reportatarija.bo', 'CITIZEN', null, true)
on conflict (email) do update set
  full_name = excluded.full_name,
  role = excluded.role,
  area_id = excluded.area_id,
  is_active = excluded.is_active,
  updated_at = now();

insert into reports (
  id, title, description, category_id, citizen_id, assigned_to, assigned_area_id,
  status, latitude, longitude, address, neighborhood, priority, created_at, updated_at, resolved_at
) values
  (
    '10000000-0000-4000-8000-000000000001',
    'Bache en Av. Las Americas',
    'Bache profundo que dificulta el paso vehicular.',
    (select id from categories where code = 'BACHE'),
    '00000000-0000-4000-8000-000000000004',
    null,
    (select id from areas where code = 'OBRAS_PUBLICAS'),
    'PENDIENTE',
    -21.53546000,
    -64.72956000,
    'Av. Las Americas',
    'Las Panosas',
    'ALTA',
    now() - interval '5 days',
    now() - interval '5 days',
    null
  ),
  (
    '10000000-0000-4000-8000-000000000002',
    'Luminaria danada en barrio Senac',
    'Poste sin iluminacion desde hace varias noches.',
    (select id from categories where code = 'ALUMBRADO_PUBLICO'),
    '00000000-0000-4000-8000-000000000004',
    '00000000-0000-4000-8000-000000000003',
    (select id from areas where code = 'ALUMBRADO_PUBLICO'),
    'EN_REVISION',
    -21.52680000,
    -64.73740000,
    'Barrio Senac',
    'Senac',
    'MEDIA',
    now() - interval '4 days',
    now() - interval '3 days',
    null
  ),
  (
    '10000000-0000-4000-8000-000000000003',
    'Basura acumulada cerca del mercado',
    'Acumulacion de residuos en via publica.',
    (select id from categories where code = 'BASURA_ACUMULADA'),
    '00000000-0000-4000-8000-000000000004',
    null,
    (select id from areas where code = 'ASEO_URBANO'),
    'ASIGNADO',
    -21.53110000,
    -64.73190000,
    'Mercado Central',
    'Centro',
    'MEDIA',
    now() - interval '3 days',
    now() - interval '2 days',
    null
  ),
  (
    '10000000-0000-4000-8000-000000000004',
    'Fuga de agua en zona San Bernardo',
    'Fuga visible en la acera con perdida constante.',
    (select id from categories where code = 'FUGA_DE_AGUA'),
    '00000000-0000-4000-8000-000000000004',
    '00000000-0000-4000-8000-000000000002',
    (select id from areas where code = 'OBRAS_PUBLICAS'),
    'EN_PROCESO',
    -21.54120000,
    -64.72410000,
    'Zona San Bernardo',
    'San Bernardo',
    'URGENTE',
    now() - interval '2 days',
    now() - interval '1 day',
    null
  ),
  (
    '10000000-0000-4000-8000-000000000005',
    'Semaforo danado en avenida principal',
    'Semaforo apagado en interseccion de alto trafico.',
    (select id from categories where code = 'SEMAFORO_DANADO'),
    '00000000-0000-4000-8000-000000000004',
    null,
    (select id from areas where code = 'MOVILIDAD_URBANA'),
    'RESUELTO',
    -21.53390000,
    -64.73560000,
    'Avenida Victor Paz Estenssoro',
    'Centro',
    'ALTA',
    now() - interval '8 days',
    now() - interval '6 days',
    now() - interval '6 days'
  ),
  (
    '10000000-0000-4000-8000-000000000006',
    'Bache cerca de colegio',
    'Reporte duplicado de bache ya atendido.',
    (select id from categories where code = 'BACHE'),
    '00000000-0000-4000-8000-000000000004',
    null,
    (select id from areas where code = 'OBRAS_PUBLICAS'),
    'RECHAZADO',
    -21.52990000,
    -64.72180000,
    'Cerca de unidad educativa',
    'La Pampa',
    'BAJA',
    now() - interval '7 days',
    now() - interval '6 days',
    null
  ),
  (
    '10000000-0000-4000-8000-000000000007',
    'Alumbrado apagado en plaza',
    'Varias luminarias apagadas alrededor de la plaza.',
    (select id from categories where code = 'ALUMBRADO_PUBLICO'),
    '00000000-0000-4000-8000-000000000004',
    null,
    (select id from areas where code = 'ALUMBRADO_PUBLICO'),
    'PENDIENTE',
    -21.53500000,
    -64.73400000,
    'Plaza principal',
    'Centro',
    'MEDIA',
    now() - interval '1 day',
    now() - interval '1 day',
    null
  ),
  (
    '10000000-0000-4000-8000-000000000008',
    'Basura en quebrada',
    'Residuos acumulados en quebrada con riesgo ambiental.',
    (select id from categories where code = 'BASURA_ACUMULADA'),
    '00000000-0000-4000-8000-000000000004',
    null,
    (select id from areas where code = 'ASEO_URBANO'),
    'EN_PROCESO',
    -21.52090000,
    -64.74220000,
    'Quebrada cercana',
    'Tabladita',
    'ALTA',
    now() - interval '2 days',
    now() - interval '12 hours',
    null
  )
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  category_id = excluded.category_id,
  citizen_id = excluded.citizen_id,
  assigned_to = excluded.assigned_to,
  assigned_area_id = excluded.assigned_area_id,
  status = excluded.status,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  address = excluded.address,
  neighborhood = excluded.neighborhood,
  priority = excluded.priority,
  updated_at = excluded.updated_at,
  resolved_at = excluded.resolved_at;

insert into evidences (report_id, file_url, file_name, file_type, uploaded_by)
select report_id, file_url, file_name, file_type, uploaded_by
from (values
  ('10000000-0000-4000-8000-000000000001'::uuid, 'https://placehold.co/900x600?text=Bache+Av+Las+Americas', 'bache-av-las-americas.jpg', 'image/jpeg', '00000000-0000-4000-8000-000000000004'::uuid),
  ('10000000-0000-4000-8000-000000000002'::uuid, 'https://placehold.co/900x600?text=Luminaria+Senac', 'luminaria-senac.jpg', 'image/jpeg', '00000000-0000-4000-8000-000000000004'::uuid),
  ('10000000-0000-4000-8000-000000000004'::uuid, 'https://placehold.co/900x600?text=Fuga+San+Bernardo', 'fuga-san-bernardo.jpg', 'image/jpeg', '00000000-0000-4000-8000-000000000004'::uuid)
) as evidence_seed(report_id, file_url, file_name, file_type, uploaded_by)
where not exists (
  select 1
  from evidences
  where evidences.report_id = evidence_seed.report_id
    and evidences.file_name = evidence_seed.file_name
);

insert into tracking (report_id, previous_status, new_status, comment, changed_by, created_at)
select report_id, previous_status, new_status, comment, changed_by, created_at
from (values
  ('10000000-0000-4000-8000-000000000001'::uuid, null, 'PENDIENTE', 'Reporte ciudadano registrado.', null::uuid, now() - interval '5 days'),
  ('10000000-0000-4000-8000-000000000002'::uuid, 'PENDIENTE', 'EN_REVISION', 'Reporte tomado para revision inicial.', '00000000-0000-4000-8000-000000000003'::uuid, now() - interval '3 days'),
  ('10000000-0000-4000-8000-000000000003'::uuid, 'EN_REVISION', 'ASIGNADO', 'Reporte asignado al area responsable.', '00000000-0000-4000-8000-000000000001'::uuid, now() - interval '2 days'),
  ('10000000-0000-4000-8000-000000000004'::uuid, 'ASIGNADO', 'EN_PROCESO', 'Equipo tecnico en atencion.', '00000000-0000-4000-8000-000000000002'::uuid, now() - interval '1 day'),
  ('10000000-0000-4000-8000-000000000005'::uuid, 'EN_PROCESO', 'RESUELTO', 'Semaforo restablecido.', '00000000-0000-4000-8000-000000000001'::uuid, now() - interval '6 days'),
  ('10000000-0000-4000-8000-000000000006'::uuid, 'PENDIENTE', 'RECHAZADO', 'Reporte duplicado.', '00000000-0000-4000-8000-000000000001'::uuid, now() - interval '6 days')
) as tracking_seed(report_id, previous_status, new_status, comment, changed_by, created_at)
where not exists (
  select 1
  from tracking
  where tracking.report_id = tracking_seed.report_id
    and tracking.new_status = tracking_seed.new_status
    and tracking.comment = tracking_seed.comment
);

insert into notifications (user_id, report_id, title, message, type, is_read, created_at)
select user_id, report_id, title, message, type, is_read, created_at
from (values
  (null::uuid, '10000000-0000-4000-8000-000000000001'::uuid, 'Nuevo reporte recibido', 'Se recibio un reporte de bache en Av. Las Americas.', 'INFO', false, now() - interval '5 days'),
  ('00000000-0000-4000-8000-000000000003'::uuid, '10000000-0000-4000-8000-000000000002'::uuid, 'Reporte asignado', 'Se asigno una luminaria danada para revision.', 'INFO', false, now() - interval '3 days'),
  (null::uuid, '10000000-0000-4000-8000-000000000005'::uuid, 'Reporte resuelto', 'El semaforo danado fue marcado como resuelto.', 'SUCCESS', true, now() - interval '6 days')
) as notification_seed(user_id, report_id, title, message, type, is_read, created_at)
where not exists (
  select 1
  from notifications
  where notifications.report_id = notification_seed.report_id
    and notifications.title = notification_seed.title
);
